# Generated by Django 2.2.3 on 2019-07-21 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ThrownTrash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('thrown_date', models.DateTimeField(verbose_name='when it was thrown')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Materials')),
            ],
        ),
    ]
